parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2022
  sourceType: module
  project: tsconfig.json
  ecmaFeatures:
    impliedStrict: true
    experimentalObjectRestSpread: true
plugins:
  - node
  - "@typescript-eslint"
  - import
  - unicorn
  - prettier
extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:import/typescript
  - prettier
rules:
  prettier/prettier: error
  no-debugger: error
  no-fallthrough: error
  no-console: warn
  valid-typeof: error
  yoda: error
  no-undef: off
  no-unused-vars: off
  eol-last:
    - error
    - always
  "@typescript-eslint/no-unsafe-argument": warn
  "@typescript-eslint/no-unsafe-assignment": warn
  "@typescript-eslint/no-unsafe-call": warn
  "@typescript-eslint/no-unsafe-member-access": warn
  "@typescript-eslint/no-floating-promises": warn
  "@typescript-eslint/no-extra-semi": error
  '@typescript-eslint/explicit-function-return-type': warn
  '@typescript-eslint/explicit-module-boundary-types': warn
  '@typescript-eslint/no-explicit-any': error
  "@typescript-eslint/member-delimiter-style":
    - error
    - overrides:
        interface:
          multiline:
            delimiter: semi
            requireLast: true
          singleline:
            delimiter: semi
            requireLast: false
        typeLiteral:
          multiline:
            delimiter: semi
            requireLast: true
          singleline:
            delimiter: semi
            requireLast: false
  "@typescript-eslint/array-type":
    - error
    - default: array-simple
  import/no-unresolved: warn
  import/no-deprecated: warn
  import/no-absolute-path: error
  import/no-dynamic-require: error
  import/no-self-import: error
  import/first: error
  import/no-cycle: warn
  import/order: error
  import/no-mutable-exports: error
  import/no-commonjs: error
  unicorn/prefer-node-protocol: error
  unicorn/better-regex: error
  unicorn/filename-case:
    - warn
    - cases:
        kebabCase: true
  node/no-missing-import: off
  node/no-empty-function: off
  node/no-unsupported-features/es-syntax: off
  node/no-unpublished-import: off



