version: "3.9"
volumes:
  postgres_data:

services:
  postgres:
    container_name: ucrm-db
    image: postgres:11.13-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-ucrm-db}
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASS:-pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USER:-user} -d ${DATABASE_NAME:-ucrm-db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 2s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    networks:
      ucrm:
        ipv4_address: ${NETWORK_PREFIX:-172.4}.4.3
        aliases:
          - ucrm.db.loc

  redis:
    container_name: ucrm-redis
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD:-password}
    ports:
      - ${REDIS_PORT:-6379}:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_URL=redis://ucrm.redis.loc:6379
      - "REDIS_PASSWORD:${REDIS_PASSWORD:-password}"
    networks:
      ucrm:
        ipv4_address: ${NETWORK_PREFIX:-172.4}.4.22
        aliases:
          - ucrm.redis.loc
  app:
    container_name: ucrm-app
    depends_on:
      - postgres
      - redis
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    env_file:
      - .env
    image: app:docker
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100M"
        reservations:
          cpus: "0.25"
          memory: 30M
    networks:
      ucrm:
        ipv4_address: ${NETWORK_PREFIX:-172.4}.4.10
        aliases:
          - ucrm.api.loc

networks:
  ucrm:
    name: ucrm
    ipam:
      config:
        - subnet: "${NETWORK_PREFIX:-172.4}.4.0/24"